class InternalException(Exception):
    def __self__(self, msg):
        super.__self__(msg)

